const r = { 'id': '106703', 
            'address': { 'id': '160308', 'address_lines': '8342 Eagles Nest Dr', 'city': 'Avon', 'constituent_id': '106703', 'country': 'United States', 'do_not_mail': False, 'formatted_address': '8342 Eagles Nest Dr\r\nAvon, IN  46123-8725', 'inactive': False, 'postal_code': '46123-8725', 'preferred': True, 'start': '2022-06-16T20:41:54.427', 'state': 'IN', 'type': 'Home' }, 
            'date_added': '2020-08-13T14:50:06.943-04:00', 
            'date_modified': '2024-05-02T14:50:13.627-04:00', 
            'deceased': False, 
            'email': { 
                'id': '97729', 
                'address': 'jenvolk5@aol.com', 
                'constituent_id': '106703', 
                'do_not_email': False, 
                'inactive': False, 
                'primary': False, 
                'type': 'E-mail1' }, 
            'first': 'Jennifer', 
            'fundraiser_status': 'None', 
            'gender': 'Female', 
            'gives_anonymously': False, 
            'inactive': False, 
            'last': 'Volk', 
            'lookup_id': '52727', 
            'middle': 'M.', 
            'name': 'Jennifer M. Volk', 
            'phone': { 'id': '98536', 'constituent_id': '106703', 'do_not_call': False, 'inactive': False, 'number': '(508) 655-5138', 'primary': False, 'type': 'Home' }, 
            'type': 'Individual', 
            'is_memorial': False, 
            'is_solicitor': False, 
            'no_valid_address': False, 
            'receipt_type': 'One receipt per gift', 
            'requests_no_email': False, 
            'import_id': '00001-593-0000106703', 
            'is_constituent': True }